export const patientStyles = {
    container: {
      minHeight: "100vh",
      backgroundColor: "white",
      display: "flex",
      flexDirection: "column",
    },
    header: {
      height: 80,
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "0 32px",
    },
    logo: { display: "flex", alignItems: "center", gap: 12 },
    logoIcon: {
      width: 32,
      height: 32,
      borderRadius: 12,
      backgroundColor: "#0a586c",
      color: "white",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      fontWeight: 700,
    },
    logoText: { fontWeight: 600, color: "#0f172a" },
    layout: { display: "flex", flex: 1 },
    sidebar: {
      width: 250,
      backgroundColor: "#0a586c",
      padding: "24px 20px",
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
      borderTopRightRadius: "24px",
    },
    sidebarNav: {
      display: "flex",
      flexDirection: "column",
      gap: 12,
      marginTop: 30,
    },
    sidebarItem: (active) => ({
      padding: "10px 12px",
      borderRadius: 12,
      cursor: "pointer",
      fontSize: 14,
      color: "white",
      backgroundColor: active ? "#083f4d" : "transparent",
    }),
    sidebarFooter: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      gap: 10,
      paddingTop: 16,
      marginTop: 24,
    },
    profilePic: {
      width: 40,
      height: 40,
      borderRadius: "50%",
      backgroundColor: "rgba(255,255,255,0.3)",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      fontWeight: 600,
      textTransform: "uppercase",
      color: "white",
    },
    main: { flex: 1, padding: "24px 32px" },
    grid: {
      display: "grid",
      gridTemplateColumns: "2fr 1fr",
      gridTemplateRows: "auto auto",
      gap: 24,
      position: "relative",
    },
    card: {
      background: "white",
      border: "1px solid #f1f5f9",
      borderRadius: 16,
      padding: 16,
      height: 240,
      overflowY: "auto",
      display: "flex",
      flexDirection: "column",
    },
    cardHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 24,
    },
    cardTitle: { margin: 0 },
    table: { width: "100%", borderCollapse: "collapse", fontSize: 14 },
    thead: {
      backgroundColor: "#d0f2fb",
      color: "#0a586c",
      position: "sticky",
      top: 0,
    },
    th: { padding: "8px 16px", textAlign: "left" },
    td: { padding: "8px 16px", borderTop: "1px solid #f1f5f9" },
    medCard: {
      display: "flex",
      alignItems: "center",
      gap: 12,
      border: "1px solid #f1f5f9",
      padding: 12,
      borderRadius: 12,
      marginBottom: 10,
    },
    medIcon: {
      width: 35,
      height: 35,
      borderRadius: 10,
      background: "rgba(10,88,108,0.1)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: 18,
    },
    testBtn: {
      display: "flex",
      alignItems: "center",
      gap: 12,
      padding: 12,
      borderRadius: 12,
      border: "1px solid #f1f5f9",
      marginBottom: 10,
      cursor: "pointer",
    },
    overlay: {
      position: "fixed",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: "rgba(0,0,0,0.25)",
      zIndex: 40,
    },
    visitsContainer: {
  background: "white",
  border: "1px solid #f1f5f9",
  borderRadius: 16,
  padding: 24,
  display: "flex",
  flexDirection: "column",
  gap: 24,
  maxHeight: "calc(100vh - 150px)", // keeps it within viewport
  overflow: "auto", // ensures it doesn’t leave blank white space
},

visitsTitle: {
  color: "#0a586c",
  marginBottom: 16,
},
visitsTable: {
  width: "100%",
  borderCollapse: "collapse",
  fontSize: 14,
  border: "1px solid #f1f5f9",
  tableLayout: "fixed", // ensure equal column alignment
},

visitsThead: {
  position: "sticky",
  top: 0,
  background: "#d0f2fb",
  color: "#0a586c",
  zIndex: 2,
},

visitsTh: {
  padding: "10px 16px",
  textAlign: "left",
},
visitsTd: {
  padding: "10px 16px",
  borderTop: "1px solid #f1f5f9",
},
clickableCell: {
  padding: "10px 16px",
  borderTop: "1px solid #f1f5f9",
  cursor: "pointer",
  color: "#0f172a", // same text color as table
},
popupContainer: {
  position: "fixed",
  top: 0,
  left: 0,
  width: "100%",
  height: "100%",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  zIndex: 60,
},
popup: {
  background: "white",
  borderRadius: 16,
  padding: 24,
  width: 500,
  minHeight: 200,
  boxShadow: "0 10px 25px rgba(0,0,0,0.15)",
  position: "relative",
},
closeBtn: {
  position: "absolute",
  top: 12,
  right: 12,
  border: "none",
  background: "none",
  fontSize: 22,
  cursor: "pointer",
  color: "#64748b",
},
scrollableTableWrapper: {
  maxHeight: "220px", // roughly fits ~5 rows depending on font size
  overflowY: "auto",
  position: "relative",
},

fixedThead: {
  position: "sticky",
  top: 0,
  background: "#d0f2fb",
  color: "#0a586c",
  zIndex: 2,
},
arrowLeft: {
  position: "absolute",
  top: "50%",
  left: 10,
  transform: "translateY(-50%)",
  background: "rgba(10,88,108,0.6)",
  color: "white",
  border: "none",
  borderRadius: "50%",
  width: 35,
  height: 35,
  cursor: "pointer",
},
arrowRight: {
  position: "absolute",
  top: "50%",
  right: 10,
  transform: "translateY(-50%)",
  background: "rgba(10,88,108,0.6)",
  color: "white",
  border: "none",
  borderRadius: "50%",
  width: 35,
  height: 35,
  cursor: "pointer",
},
scrollableTableWrapper: {
  maxHeight: "250px",
  overflowY: "auto",
  borderRadius: 12,
  border: "1px solid #f1f5f9",
},
popupContainer: {
  position: "fixed",
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  zIndex: 60,
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
},

};

