
export const patientStyles = {
    container: {
      minHeight: "100vh",
      backgroundColor: "white",
      display: "flex",
      flexDirection: "column",
      overflow: "hidden", 
    },
    header: {
  position: "fixed",
  top: 0,
  left: 0,
  right: 0,
  height: 70,
  background: "white",
  display: "flex",
  alignItems: "center",
  padding: "0 24px",
  borderBottom: "1px solid #E2E8F0",
  zIndex: 100,
},

logoContainer: {
  display: "flex",
  alignItems: "center",
  gap: 10,
},

logoCircle: {
  width: 34,
  height: 34,
  borderRadius: 10,
  background: "#0A586C",
  color: "white",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  fontWeight: 700,
  fontSize: 18,
},

logoWord: {
  color: "#0A586C",
  fontSize: 20,
  fontWeight: 600,
},
    logo: { display: "flex", alignItems: "center", gap: 12 },
    logoIcon: {
      width: 32,
      height: 32,
      borderRadius: 12,
      backgroundColor: "#0a586c",
      color: "white",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      fontWeight: 700,
    },
    logoText: { fontWeight: 600, color: "#0f172a" },
    layout: { display: "flex", flex: 1 },
    
  sidebar: {
  position: "fixed",
  top: 70,
  left: 0,
  width: "230px",
  height: "calc(100vh - 70px)",
  background: "#0A586C",
  borderTopRightRadius: "40px", 
  display: "flex",
  flexDirection: "column",
  justifyContent: "space-between",
  padding: "20px 0",
  zIndex: 150,
  overflow: "hidden",
},

    sidebarNav: {
      display: "flex",
      flexDirection: "column",
      gap: 12,
      marginTop: 55,
      alignItems: "flex-start", 
  paddingLeft: "20px",     
    },
    sidebarItem: (active) => ({
      padding: "10px 12px",
      borderRadius: 12,
      cursor: "pointer",
      fontSize: 19,
      color: "white",
      backgroundColor: active ? "#083f4d" : "transparent",
    }),
    sidebarFooter: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      gap: 10,
      marginBottom: 20,
      marginLeft: 20,
    },
    profilePic: {
      width: 60,
      height: 60,
      borderRadius: "50%",
      backgroundColor: "rgba(255,255,255,0.3)",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      fontWeight: 600,
      textTransform: "uppercase",
      color: "white",
    },
   main: {
  flex: 1,
  marginLeft: "230px", 
  marginTop: "80px", 
  height: "calc(100vh - 70px)",
  overflowY: "auto",
  backgroundColor: "white",
  padding: " 24px 32px",
},
    grid: {
      display: "grid",
      gridTemplateColumns: "2fr 1fr",
      gridTemplateRows: "auto auto",
      gap: 24,
      position: "relative",
    },
    card: {
      background: "white",
      border: "1px solid #f1f5f9",
      borderRadius: 16,
      padding: 16,
      height: 240,
      overflowY: "auto",
      display: "flex",
      flexDirection: "column",
    },
    cardHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 24,
    },
    cardTitle: { margin: 0 },
    table: { width: "100%", borderCollapse: "collapse", fontSize: 14 },
    thead: {
      backgroundColor: "#d0f2fb",
      color: "#0a586c",
      position: "sticky",
      top: 0,
    },
    th: { padding: "8px 16px", textAlign: "left" },
    td: { padding: "8px 16px", borderTop: "1px solid #f1f5f9" },
    medCard: {
      display: "flex",
      alignItems: "center",
      gap: 12,
      border: "1px solid #f1f5f9",
      padding: 12,
      borderRadius: 12,
      marginBottom: 10,
    },
    medIcon: {
      width: 35,
      height: 35,
      borderRadius: 10,
      background: "rgba(10,88,108,0.1)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: 18,
    },
    testBtn: {
      display: "flex",
      alignItems: "center",
      gap: 12,
      padding: 12,
      borderRadius: 12,
      border: "1px solid #f1f5f9",
      marginBottom: 10,
      cursor: "pointer",
    },
    overlay: {
      position: "fixed",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: "rgba(0,0,0,0.25)",
      zIndex: 40,
    },
    visitsContainer: {
  background: "white",
  border: "1px solid #f1f5f9",
  borderRadius: 16,
  padding: 24,
  display: "flex",
  flexDirection: "column",
  gap: 24,
  maxHeight: "calc(100vh - 150px)", 
  overflow: "auto", 
},

visitsTitle: {
  color: "#0a586c",
  marginBottom: 16,
},
visitsTable: {
  width: "100%",
  borderCollapse: "collapse",
  fontSize: 14,
  border: "1px solid #f1f5f9",
  tableLayout: "fixed", 
},

visitsThead: {
  position: "sticky",
  top: 0,
  background: "#d0f2fb",
  color: "#0a586c",
  zIndex: 2,
},

visitsTh: {
  padding: "10px 16px",
  textAlign: "left",
},
visitsTd: {
  padding: "10px 16px",
  borderTop: "1px solid #f1f5f9",
},
clickableCell: {
  padding: "10px 16px",
  borderTop: "1px solid #f1f5f9",
  cursor: "pointer",
  color: "#0f172a", 
},

popup: {
  background: "white",
  borderRadius: 16,
  padding: 24,
  width: 500,
  minHeight: 200,
  boxShadow: "0 10px 25px rgba(0,0,0,0.15)",
  position: "relative",
},
closeBtn: {
  position: "absolute",
  top: 12,
  right: 12,
  border: "none",
  background: "none",
  fontSize: 22,
  cursor: "pointer",
  color: "#64748b",
},


fixedThead: {
  position: "sticky",
  top: 0,
  background: "#d0f2fb",
  color: "#0a586c",
  zIndex: 2,
},
arrowLeft: {
  position: "absolute",
  top: "50%",
  left: 10,
  transform: "translateY(-50%)",
  background: "rgba(10,88,108,0.6)",
  color: "white",
  border: "none",
  borderRadius: "50%",
  width: 35,
  height: 35,
  cursor: "pointer",
},
arrowRight: {
  position: "absolute",
  top: "50%",
  right: 10,
  transform: "translateY(-50%)",
  background: "rgba(10,88,108,0.6)",
  color: "white",
  border: "none",
  borderRadius: "50%",
  width: 35,
  height: 35,
  cursor: "pointer",
},
scrollableTableWrapper: {
  maxHeight: "250px",
  overflowY: "auto",
  borderRadius: 12,
  border: "1px solid #f1f5f9",
},

popupContainer: {
  position: "fixed",
  top: 0,
  left: 0,
  width: "100vw",
  height: "100vh",
  zIndex: 9999,
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  background: "rgba(0,0,0,0.25)",
},

profileContainer: {
  display: "grid",
  gridTemplateColumns: "1fr 1fr",
  gap: 24,
  padding: "0 16px",
},

profileContent: {
  display: "flex",
  flexDirection: "column",
  gap: 12,
},

cardTitle: {
  color: "#0A586C",
  fontWeight: 700,
  fontSize: "18px",
  marginBottom: "16px",
},

sectionHeader: {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  marginBottom: "12px",
},

editIcon: {
  cursor: "pointer",
  fontSize: "18px",
  color: "#0A586C",
},

profilePhoto: {
  width: "120px",
  height: "120px",
  borderRadius: "50%",
  objectFit: "cover",
  display: "block",
  margin: "0 auto 16px auto",
  border: "2px solid #C9F1FB",
},


profilePage: {
  display: "grid",
  gridTemplateColumns: "1fr 1fr",
  gap: 24,
  padding: "0 16px",
  color: "#0a586c",
},

leftColumn: { display: "flex", flexDirection: "column", gap: 24 },
rightColumn: { display: "flex", flexDirection: "column", gap: 24 },

profileCard: {
  background: "white",
  borderRadius: 16,
  padding: 24,
  border: "1px solid #e2e8f0",
  boxShadow: "0 4px 10px rgba(0,0,0,0.05)",
},

cardTitle: { fontWeight: 600, color: "#0a586c", fontSize: 18 },

sectionHeader: {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  marginBottom: 12,
},

editIcon: {
  fontSize: 16,
  color: "#0a586c",
  cursor: "pointer",
},

profilePhoto: {
  width: 140,
  height: 140,
  borderRadius: "50%",
  objectFit: "cover",
  margin: "12px auto",
  border: "3px solid #d0f2fb",
  display: "block",
},

uploadBtn: {
  display: "inline-block",
  background: "#0A586C",
  color: "#FFFFFF",
  border: "none",
  borderRadius: "6px",
  padding: "5px 10px", 
  cursor: "pointer",
  fontSize: "13px",
  fontWeight: 500,
  margin: "0 200px",
  textAlign: "center",
},


infoRow: {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  fontSize: 14,
  borderBottom: "1px solid #f1f5f9",
  padding: "8px 0",
},

inputField: {
  border: "1px solid #d0f2fb",
  borderRadius: 8,
  padding: "4px 8px",
  fontSize: 14,
  width: "50%",
},



nav: { display: "flex", flexDirection: "column", gap: 12 },

navItem: {
  display: "flex",
  alignItems: "center",
  gap: 12,
  padding: "10px 20px",
  border: "none",
  background: "transparent",
  color: "white",
  fontSize: 15,
  cursor: "pointer",
},

icon: { fontSize: 18 },
iconImg: { width: 18, height: 18, filter: "invert(1)" },
logoutBtn: {
  marginLeft: 20,
  display: "flex",
  alignItems: "center",
  gap: 12,
  background: "transparent",
  color: "white",
  border: "none",
  cursor: "pointer",
},

profileHeader: {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  width: "100%",
  marginBottom: "25px",
  padding: "0 40px",
},

profileTitle: {
  color: "black",
  fontSize: 26,
  fontWeight: 600,
  margin: 0,
},

editButton: {
  background: "#0a586c",
  color: "white",
  border: "none",
  borderRadius: 16,
  padding: "8px 20px",
  fontSize: 14,
  cursor: "pointer",
},

changePasswordCard: {
  background: "white",
  border: "1px solid #e2e8f0",
  borderRadius: 16,
  padding: 24,
  boxShadow: "0 4px 10px rgba(0,0,0,0.05)",
  width: "100%",
  maxWidth: 500,
  margin: "20px auto",
  display: "flex",
  flexDirection: "column",
  gap: 16,
},

passwordInput: {
  border: "1px solid #d0f2fb",
  borderRadius: 8,
  padding: "8px 12px",
  fontSize: 14,
  width: "100%",
  outline: "none",
},

changePasswordButton: {
  background: "#0a586c",
  color: "white",
  border: "none",
  borderRadius: 12,
  padding: "10px 20px",
  fontSize: 14,
  cursor: "pointer",
  alignSelf: "flex-end",
},
changePasswordTrigger: {
  color: "#0A586C",
  fontWeight: 600,
  cursor: "pointer",
  marginTop: 10,
  textAlign: "left",
  padding: "8px 0",
},

changePasswordCard: {
  background: "white",
  border: "1px solid #e2e8f0",
  borderRadius: 16,
  padding: 24,
  boxShadow: "0 4px 10px rgba(0,0,0,0.05)",
  width: "100%",
  marginTop: 16,
  display: "flex",
  flexDirection: "column",
  gap: 12,
},

passwordRow: {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  gap: 12,
},

passwordLabel: {
  flex: "0 0 160px",
  fontSize: 14,
  color: "#0F172A",
  fontWeight: 500,
},

passwordInput: {
  flex: 1,
  border: "1px solid #D0F2FB",
  borderRadius: 8,
  padding: "6px 10px",
  fontSize: 14,
  outline: "none",
},

changePasswordButton: {
  background: "#0A586C",
  color: "white",
  border: "none",
  borderRadius: 12,
  padding: "8px 20px",
  fontSize: 14,
  cursor: "pointer",
  alignSelf: "flex-end",
  marginTop: 10,
},

errorText: {
  color: "#E53E3E",
  fontSize: 13,
  marginTop: 4,
},

scanPopup: {
  display: "flex",
  flexDirection: "row",
  width: "80%",
  height: "70%",
  background: "white",
  borderRadius: 16,
  overflow: "hidden",
  boxShadow: "0 10px 25px rgba(0,0,0,0.2)",
  zIndex: 10000,
},

scanLeft: {
  flex: 1,
  position: "relative",
  background: "#f9fafb",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
},

scanRight: {
  flex: 1,
  padding: 24,
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  color: "#0a586c",
},

scanImage: {
  maxWidth: "90%",
  maxHeight: "90%",
  borderRadius: 12,
  objectFit: "contain",
  boxShadow: "0 4px 10px rgba(0,0,0,0.1)",
},

scanTitle: {
  fontSize: 20,
  fontWeight: 700,
  marginBottom: 12,
},

scanReport: {
  fontSize: 15,
  lineHeight: 1.5,
  color: "#334155",
},

arrowBtn: {
  position: "absolute",
  top: "50%",
  transform: "translateY(-50%)",
  background: "rgba(10,88,108,0.7)",
  color: "white",
  border: "none",
  borderRadius: "50%",
  width: 40,
  height: 40,
  fontSize: 22,
  cursor: "pointer",
  zIndex: 10,
},


};

